name: SEARCH

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

env:
    TELEGRAM: ${{ secrets.TELEGRAM }}
    CHAT_ID: ${{ secrets.CHAT_ID }}
    URL: ${{ secrets.URL }}

jobs:
  SEARCH:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: First try
        if: always()
        run:  ./ovhvps.ps1
